// <auto-generated />
using System;
using AssetManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssetManager.Migrations
{
    [DbContext(typeof(AssetsDbContext))]
    [Migration("20220514055152_Initial Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("AssetManager.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcquiredOn = new DateTime(2022, 5, 14, 7, 51, 52, 165, DateTimeKind.Local).AddTicks(3213),
                            CurrentUser = 1,
                            Manufacturer = "Samsung",
                            Name = "Samsung Galaxy M11",
                            SerialNumber = "0094KC029M",
                            Type = "smartphone"
                        },
                        new
                        {
                            Id = 2,
                            AcquiredOn = new DateTime(2022, 5, 14, 7, 51, 52, 166, DateTimeKind.Local).AddTicks(9743),
                            CurrentUser = 2,
                            Manufacturer = "Samsung",
                            Name = "Samsung Galaxy Tab S4-A",
                            SerialNumber = "099393V54VT",
                            Type = "tablet"
                        },
                        new
                        {
                            Id = 3,
                            AcquiredOn = new DateTime(2022, 5, 14, 7, 51, 52, 166, DateTimeKind.Local).AddTicks(9774),
                            CurrentUser = 1,
                            Manufacturer = "Lenovo",
                            Name = "Lenovo Thinkpad T480s",
                            SerialNumber = "PC3029m4",
                            Type = "laptop"
                        },
                        new
                        {
                            Id = 4,
                            AcquiredOn = new DateTime(2022, 5, 14, 7, 51, 52, 166, DateTimeKind.Local).AddTicks(9778),
                            CurrentUser = 3,
                            Manufacturer = "Apple",
                            Name = "Mac Book Pro Express",
                            SerialNumber = "MC343302",
                            Type = "laptop"
                        });
                });

            modelBuilder.Entity("AssetManager.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "infrastructure development",
                            JoinedOn = new DateTime(2022, 5, 14, 7, 51, 52, 458, DateTimeKind.Local).AddTicks(6478),
                            UserId = new Guid("1ff70d72-526d-4ed1-8652-b6d5316d2cdc"),
                            Username = "Tinashe Chitakunye"
                        },
                        new
                        {
                            Id = 2,
                            Department = "infrastructure development",
                            JoinedOn = new DateTime(2022, 5, 14, 7, 51, 52, 458, DateTimeKind.Local).AddTicks(6949),
                            UserId = new Guid("607f7b3e-77dd-4232-aa5a-711b56fa3ae8"),
                            Username = "Kimberly Manyonga"
                        },
                        new
                        {
                            Id = 3,
                            Department = "infrastructure development",
                            JoinedOn = new DateTime(2022, 5, 14, 7, 51, 52, 458, DateTimeKind.Local).AddTicks(6956),
                            UserId = new Guid("0221a8af-de8b-497c-a8b0-e9960526a0bb"),
                            Username = "Richard Dzingai"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
